name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install common-modules
      run: |
        npm ci
      working-directory: ./common-modules/nodejs
      env:
        CI: true
    - name: Install, test shared-functions
      run: |
        npm ci
        npm run test
      working-directory: ./shared-functions
      env:
        CI: true
    - name: Test users package
      run: |
        ln -s ../common-modules/nodejs/node_modules/ node_modules
        ln -s ../shared-functions/ opt
        npm run test
      working-directory: ./users
      env:
        CI: true
